amp: true
exps: models
output_path: "$'/workspace/vista3d/' + @exps"
dataset_name: "TotalSegmentatorV2"
label_set: null
json_name: "$@dataset_name + '_5_folds.json'"
data_file_base_dir: "$'/data/' + @dataset_name"
data_list_file_path: "$'./data/jsons/' + @json_name"
log_output_file: "$@output_path + '/validation_auto_' + @dataset_name + '.log'"
list_key: 'testing'
argmax_first: false
fold: 0
image_key: image
label_key: label
transforms_infer:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    ensure_channel_first: true
    image_only: true
    keys: ['@image_key','@label_key']
  - _target_: CopyItemsd
    names: 'label_gt'
    keys: '@label_key'
  - {_target_: ScaleIntensityRanged, a_max: 1000, a_min: -1000,
    b_max: 255, b_min: 0, clip: true, keys: '@image_key'}
  - _target_: CastToTyped
    dtype: [$torch.float32, $torch.uint8]
    keys: ['@image_key','@label_key']
  - _target_: EnsureTyped
    keys: ['@image_key','@label_key']
    track_meta: true
model: "vista3d_segresnet_d"
